version: '3.8'

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./swap/:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  mysql_data:
