# docker-compose.yml

version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: prod.Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 swap.wsgi:application
    volumes:
      - ./swap/:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=swap.settings
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: