# Generated by Django 5.1.1 on 2024-09-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pseudo', models.CharField(max_length=100)),
                ('id_entite', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArboLink',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_arborescence', models.IntegerField()),
            ],
            options={
                'db_table': 'f_produits_machine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'contrats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_entite', models.IntegerField()),
                ('message', models.TextField()),
                ('for_particulier', models.BooleanField()),
                ('for_station', models.BooleanField()),
                ('for_distributeur', models.BooleanField()),
                ('ts_creation', models.IntegerField()),
            ],
            options={
                'db_table': 'discussions_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_fournisseur', models.IntegerField()),
                ('id_admin', models.IntegerField()),
                ('id_depot', models.IntegerField()),
                ('id_station', models.IntegerField()),
                ('id_etablissement', models.IntegerField()),
                ('id_distributeur', models.IntegerField()),
                ('id_societe', models.IntegerField()),
                ('societe', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'entites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_ticket', models.IntegerField()),
                ('ts', models.IntegerField()),
            ],
            options={
                'db_table': 'support_tickets_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tr_nom', models.IntegerField()),
            ],
            options={
                'db_table': 'support_tickets_logs_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'marques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=50)),
                ('poids', models.FloatField()),
                ('code_barres', models.CharField(max_length=13)),
                ('tr_nom', models.IntegerField()),
                ('dpr', models.FloatField()),
            ],
            options={
                'db_table': 'produits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SwapEntity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_entite', models.IntegerField()),
            ],
            options={
                'db_table': 'f_entites_swap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_discussion', models.IntegerField()),
                ('id_particulier', models.IntegerField()),
                ('read', models.BooleanField()),
                ('ts_message', models.IntegerField()),
                ('is_removed', models.BooleanField()),
                ('is_admin_closure', models.BooleanField()),
                ('ts_creation', models.IntegerField()),
                ('statut', models.IntegerField()),
                ('date_claim', models.DateTimeField()),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'support_tickets_contrat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'support_tickets_statuts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tr_title', models.IntegerField()),
            ],
            options={
                'db_table': 'support_tickets_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fr', models.TextField()),
                ('en', models.TextField()),
                ('ru', models.TextField()),
            ],
            options={
                'db_table': 'translate',
                'managed': False,
            },
        ),
    ]
